# Generated by Django 4.2.10 on 2024-03-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_rating_alter_story_author_alter_story_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorrorGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
