# Generated by Django 4.2.10 on 2024-03-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_horrorgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorrorGenre',
        ),
        migrations.AddField(
            model_name='comment',
            name='genre',
            field=models.CharField(choices=[('supernatural', 'Supernatural Horror'), ('psychological', 'Psychological Horror'), ('slasher', 'Slasher'), ('zombie', 'Zombie Apocalypse'), ('found_footage', 'Found Footage'), ('monster', 'Monster'), ('survival', 'Survival Horror')], default='supernatural', max_length=20),
            preserve_default=False,
        ),
    ]
