# Generated by Django 4.2.10 on 2024-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
