# Generated by Django 4.2.10 on 2024-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_story_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_upload',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Image'),
        ),
    ]
