# Generated by Django 4.2.10 on 2024-03-22 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('supernatural', 'Supernatural Horror'), ('psychological', 'Psychological Horror'), ('slasher', 'Slasher'), ('zombie', 'Zombie Apocalypse'), ('found_footage', 'Found Footage'), ('monster', 'Monster'), ('survival', 'Survival Horror')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
