# Generated by Django 4.2.10 on 2024-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('supernatural', 'Supernatural Horror'), ('psychological', 'Psychological Horror'), ('slasher', 'Slasher'), ('zombie', 'Zombie Apocalypse'), ('found_footage', 'Found Footage'), ('monster', 'Monster'), ('survival', 'Survival Horror')], max_length=50),
        ),
    ]
