# Generated by Django 4.2.10 on 2024-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_alter_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='genre',
            field=models.CharField(choices=[('supernatural', 'Supernatural Horror'), ('psychological', 'Psychological Horror'), ('slasher', 'Slasher'), ('zombie', 'Zombie Apocalypse'), ('found_footage', 'Found Footage'), ('monster', 'Monster'), ('survival', 'Survival Horror')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('supernatural', 'Supernatural Horror'), ('psychological', 'Psychological Horror'), ('slasher', 'Slasher'), ('zombie', 'Zombie Apocalypse'), ('found_footage', 'Found Footage'), ('monster', 'Monster'), ('survival', 'Survival Horror')], default=0, max_length=20),
        ),
    ]
